import type { Metadata } from "next";
import { LegalDocument, LegalDraftBanner, type LegalSection } from "@/components/legal-document";

export const metadata: Metadata = { title: "Terms of Service" };

const sections: LegalSection[] = [
  {
    heading: "1. Who this agreement is with",
    paragraphs: [
      <>These terms are between you and [LEGAL ENTITY NAME], operator of Buildstory (the website, the <code>buildstory</code> command-line tool, and related services — together, the &ldquo;Service&rdquo;). By creating an account or using the Service you agree to these terms and to our <a href="/privacy">Privacy Policy</a>.</>,
    ],
  },
  {
    heading: "2. What Buildstory is",
    paragraphs: [
      "Buildstory lets people who build software with AI coding agents publish a verified “build story”: a public page combining their own written narrative with structural facts derived from their local Git history and local AI coding-session data (session counts, commit counts, model mix, and similar figures), generated by a scanner that runs on their own machine and sends only redacted, aggregate data — never source code, prompts, or file contents — unless they separately opt in to a narrative-generation feature described in the Privacy Policy.",
    ],
  },
  {
    heading: "3. Accounts",
    list: [
      "You need a Google account to sign in. You're responsible for keeping your account secure and for all activity under it.",
      "Your handle must be your own, must not impersonate anyone else, and is subject to [CONFIRM: a reserved-word/trademark policy if you want one beyond the technical reserved-handle list already enforced].",
      "You must be at least [CONFIRM AGE, e.g. 13, or higher per your jurisdiction] to use the Service.",
    ],
  },
  {
    heading: "4. Your content",
    list: [
      <><strong>You own what you publish.</strong> Your build stories, comments, and any other content you submit (&ldquo;Your Content&rdquo;) remain yours.</>,
      <><strong>License you grant us:</strong> by publishing Your Content, you grant Buildstory a worldwide, non-exclusive, royalty-free license to host, display, and distribute it as part of operating the Service (e.g. showing your published story to other visitors, including it in a feed or leaderboard). This license ends when you unpublish or delete the content, except for residual copies that reasonably persist in backups until they cycle out.</>,
      <><strong>AI-generated narrative text:</strong> if you opt into AI narrative generation, the resulting headline/narrative/turning-point/learnings text is treated the same as content you wrote — it&rsquo;s sanitized before storage, but you review and can edit it, and you&rsquo;re responsible for what you choose to publish. [CONFIRM: your position on ownership of AI-generated text — norms and law here are still unsettled; get counsel&rsquo;s view before asserting anything definitive.]</>,
      <><strong>What you must not publish:</strong> content that&rsquo;s unlawful, infringing, harassing, or that discloses someone else&rsquo;s private information without consent (including secrets, credentials, or private repository contents you might paste into a comment — remember the scanner&rsquo;s own redaction guarantees do not apply to text you type directly into comments).</>,
    ],
  },
  {
    heading: "5. Moderation and enforcement",
    list: [
      "Any signed-in user can report a comment, a story, or a profile for review (spam, harassment, impersonation, malicious content, or other).",
      "We may remove content, suspend, or terminate accounts that violate these terms, at our discretion. [CONFIRM: whether you want to commit to a specific appeals process or response-time SLA — none exists today beyond the ability to file a report.]",
      "Removed comments may be shown as “[deleted]” rather than fully erased from the page, to preserve the surrounding conversation for other participants; the comment's own text is discarded either way.",
    ],
  },
  {
    heading: "6. Account deletion",
    paragraphs: [
      "You can permanently delete your account and everything tied to it (profile, projects, published stories, comments, reactions, follow relationships) from Settings at any time. This is immediate and cannot be undone — see the Privacy Policy for exactly what is removed.",
    ],
  },
  {
    heading: "7. Leaderboards and rankings",
    paragraphs: [
      "Leaderboard rank is computed from verified, structural build activity (commits, active days) across your published stories, with a per-project daily cap specifically so a single burst of activity can't dominate a ranking meant to reflect sustained work. [CONFIRM: whether you want to reserve the right to adjust the ranking methodology, exclude accounts found to be gaming it outside the built-in cap, or reset rankings — state your policy here if so.]",
    ],
  },
  {
    heading: "8. Disclaimers",
    paragraphs: [
      "[CONFIRM WITH COUNSEL — standard boilerplate below, not a substitute for jurisdiction-appropriate legal language:]",
      "The Service is provided “as is” without warranties of any kind. We don't guarantee the Service will be uninterrupted, secure, or error-free, or that any AI-generated content will be accurate.",
    ],
  },
  {
    heading: "9. Limitation of liability",
    paragraphs: [
      "[CONFIRM WITH COUNSEL — this section carries real legal weight and must reflect your actual risk tolerance and jurisdiction; do not publish placeholder liability caps as if they were considered.]",
    ],
  },
  {
    heading: "10. Governing law and disputes",
    paragraphs: [
      "[CONFIRM: choice of law, venue, and whether you want an arbitration clause or class-action waiver — all jurisdiction-specific decisions for counsel, not defaults to invent here.]",
    ],
  },
  {
    heading: "11. Changes to these terms",
    paragraphs: [
      "[CONFIRM: how you'll notify users of material changes before publishing — e.g. an in-app notice and an updated “Effective date” above.]",
    ],
  },
  {
    heading: "12. Contact",
    paragraphs: ["[CONFIRM: a real contact email/address for legal notices.]"],
  },
];

export default function TermsPage() {
  return (
    <section className="legal-page section-wrap">
      <span className="section-index">( TERMS )</span>
      <h1>Terms of Service</h1>
      <LegalDraftBanner />
      <LegalDocument preparedDate="2026-08-05" sections={sections} />
    </section>
  );
}
