import Link from "next/link";
import type { NarrativeMode } from "@/lib/ingestion/scanner-project-snapshot";

type DisclosurePoints = {
  readLocally: string;
  leavesMachine: string;
  whoReceivesIt: string;
  redactedFirst: string;
  storedAndRemoval: string;
};

/**
 * Copy is derived from packages/buildstory-scanner/src/privacy-boundary.ts
 * (the redaction categories: remote-url, raw-host, absolute-path,
 * relative-file-path, plus the known-secret-format list in redaction.ts)
 * and packages/buildstory-scanner/docs/privacy.md, so this disclosure and
 * the scanner's actual behavior cannot drift apart silently - if the
 * redaction boundary changes, this text should change with it.
 */
const REDACTED_FIRST = "File paths, URLs, and hostnames are replaced with category placeholders (e.g. [absolute-path], [remote-url]) before anything leaves this machine, alongside known secret formats (API keys, JWTs, OAuth tokens, PEM private keys, and similar) - see the scanner's redaction boundary. This never depends on what you selected above; it runs the same way in every mode.";

const POINTS: Record<NarrativeMode, DisclosurePoints> = {
  local: {
    readLocally: "Your local Git history and local AI coding-session files (Claude Code, Codex, Cursor, Google Antigravity) for the repository you scan.",
    leavesMachine: "Deterministic metrics, profile scores, and redacted AI-written narrative prose generated by a small model running on this machine through Ollama. Conversation excerpts stay in this process's memory during generation and are never uploaded.",
    whoReceivesIt: "Buildstory only.",
    redactedFirst: REDACTED_FIRST,
    storedAndRemoval: "Stored as a private report until you choose to publish it. Delete it from your project, or delete your whole account from Settings, to remove it permanently.",
  },
  byok: {
    readLocally: "Your local Git history and local AI coding-session files for the repository you scan.",
    leavesMachine: "A small, size-capped set of redacted conversation excerpts, sent from this machine directly to the cloud model you configured with your own API key (never through Buildstory). The resulting narrative prose it writes is then redacted and uploaded, exactly like Local mode.",
    whoReceivesIt: "The cloud provider you configured (under that provider's own terms), then Buildstory - but Buildstory never sees the excerpts or your key, only the resulting redacted prose.",
    redactedFirst: REDACTED_FIRST,
    storedAndRemoval: "Stored as a private report until you choose to publish it. Delete it from your project, or delete your whole account from Settings, to remove it permanently.",
  },
  cloud: {
    readLocally: "Your local Git history and local AI coding-session files for the repository you scan.",
    leavesMachine: "A small, size-capped set of redacted conversation excerpts - only after you review the exact excerpts printed on screen and type a confirmation to release them.",
    whoReceivesIt: "Buildstory, which forwards the reviewed excerpts to our configured cloud model provider to write the narrative.",
    redactedFirst: REDACTED_FIRST,
    storedAndRemoval: "Stored as a private report until you choose to publish it. Delete it from your project, or delete your whole account from Settings, to remove it permanently.",
  },
  off: {
    readLocally: "Your local Git history and local AI coding-session files for the repository you scan.",
    leavesMachine: "Deterministic metrics and profile scores only - no AI narrative generation runs, so no conversation excerpts are ever selected, read, or sent anywhere.",
    whoReceivesIt: "Buildstory only.",
    redactedFirst: REDACTED_FIRST,
    storedAndRemoval: "Stored as a private report until you choose to publish it. Delete it from your project, or delete your whole account from Settings, to remove it permanently.",
  },
};

export function NarrativeModeDisclosure({ mode }: { mode: NarrativeMode }) {
  const points = POINTS[mode];
  return (
    <dl className="narrative-mode-disclosure" aria-live="polite">
      <div><dt>What&rsquo;s read on this machine</dt><dd>{points.readLocally}</dd></div>
      <div><dt>What leaves this machine</dt><dd>{points.leavesMachine}</dd></div>
      <div><dt>Who receives it</dt><dd>{points.whoReceivesIt}</dd></div>
      <div><dt>Redacted first</dt><dd>{points.redactedFirst}</dd></div>
      <div><dt>Stored, and how to remove it</dt><dd>{points.storedAndRemoval}</dd></div>
      <p className="narrative-mode-disclosure__footnote">
        This choice is saved in this browser only, not on your account - it will reset to Local on a new device. Read the full <Link href="/privacy">Privacy Policy</Link> for everything else Buildstory collects.
      </p>
    </dl>
  );
}
