import assert from "node:assert/strict";
import test from "node:test";
import { canonicalizeGitRemote, repositoryFingerprintFromRemote, sha256Fingerprint } from "../lib/repository-fingerprint";

// These input/output pairs were generated by running the scanner's actual,
// unmodified canonicalizeRemote() + sha256() (buildstory-scan src/
// repository.ts, canonical-json.ts) against each input in a standalone Node
// script - not re-derived from this module's own logic - so this test proves
// byte-for-byte parity with the scanner, not just internal self-consistency.
const scpLikeSsh = "git@github.com:Example-Owner/Example-Repo.git";
const httpsUrl = "https://github.com/Example-Owner/Example-Repo.git";
const httpsUrlTrailingSlash = "https://github.com/Example-Owner/Example-Repo/";
const mixedCaseHost = "https://GITHUB.com/octocat/Hello-World";
const explicitSshScheme = "ssh://git@github.com/octocat/Hello-World.git";
const fileUrl = "file:///home/user/project";
const notAUrl = "not a url";

test("canonicalizeGitRemote matches the scanner's own output for real SCP-like ssh remotes", () => {
  assert.deepEqual(canonicalizeGitRemote(scpLikeSsh), { host: "github.com", path: "Example-Owner/Example-Repo" });
});

test("canonicalizeGitRemote reproduces the scanner's known bug for scheme://... remotes (host becomes the scheme, not the real hostname)", () => {
  // This looks wrong, and it is - see the doc comment on canonicalizeGitRemote.
  // It is intentionally pinned to the scanner's actual current behavior.
  assert.deepEqual(canonicalizeGitRemote(httpsUrl), { host: "https", path: "github.com/Example-Owner/Example-Repo" });
  assert.deepEqual(canonicalizeGitRemote(httpsUrlTrailingSlash), { host: "https", path: "github.com/Example-Owner/Example-Repo" });
  assert.deepEqual(canonicalizeGitRemote(mixedCaseHost), { host: "https", path: "GITHUB.com/octocat/Hello-World" });
  assert.deepEqual(canonicalizeGitRemote(explicitSshScheme), { host: "ssh", path: "git@github.com/octocat/Hello-World" });
});

test("canonicalizeGitRemote falls through to null only for genuinely unparseable strings; file: URLs hit the same scheme-as-host bug (see above), same as the scanner", () => {
  // The file: guard in the URL-fallback branch is effectively dead code today,
  // because the SCP-like regex above it already matches any "scheme:..."
  // input first - this mirrors that exactly, bug included.
  assert.deepEqual(canonicalizeGitRemote(fileUrl), { host: "file", path: "home/user/project" });
  assert.equal(canonicalizeGitRemote(notAUrl), null);
});

test("sha256Fingerprint matches the scanner's sha256() hex digest byte-for-byte", async () => {
  assert.equal(
    await sha256Fingerprint("github.com/Example-Owner/Example-Repo"),
    "sha256:66b817a0a38aa834855b9fa4a5a1afd67ce3c2263307544f12ec1bf901879e3b",
  );
});

test("repositoryFingerprintFromRemote composes canonicalization + hashing exactly like the scanner's inspectRepository()", async () => {
  assert.equal(
    await repositoryFingerprintFromRemote(scpLikeSsh),
    "sha256:66b817a0a38aa834855b9fa4a5a1afd67ce3c2263307544f12ec1bf901879e3b",
  );
  assert.equal(
    await repositoryFingerprintFromRemote(httpsUrl),
    "sha256:85de43cbd87812949806d99aa4c1cb1e0a832b9150f0779ef4ac7459203c71b1",
  );
  assert.equal(await repositoryFingerprintFromRemote(notAUrl), null);
});
